# Generated by Django 3.2.3 on 2021-05-29 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='files',
        ),
        migrations.AddField(
            model_name='message',
            name='files',
            field=models.ManyToManyField(related_name='message', to='main.Attatchments'),
        ),
    ]
