# Generated by Django 3.2.3 on 2021-05-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210529_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='files',
            field=models.ManyToManyField(blank=True, null=True, related_name='message', to='main.Attatchments'),
        ),
        migrations.AlterField(
            model_name='message',
            name='heading',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='tags',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
